### ISSUE TITLE
Won't Start

### ISSUE THREAD

**Issue by levone1** [mzanetti/machines-vs-machines-sfos#1]
Hi. Built for aarch64 on Sailfish 4.3, and opens to home screen, but won't start...
Terminal shows:
`D] unknown:0 - setting levelpack “”
[W] unknown:130 - file:///usr/share/harbour
-machines-vs-machines-sfos/qml/harbour-mach
ines-vs-machines-sfos.qml:130: TypeError: C
annot read property ‘titleSound’ of null
[D] onStatusChanged:43 - Loader MainPage.qm
l status changed: Ready
[W] unknown:12 - file:///usr/share/harbour-
machines-vs-machines-sfos/qml/components/Le
velPackCarousel.qml:12: TypeError: Cannot r
ead property ‘levelPackId’ of null`

**Comment by poetaster** [comment]
Starts fine if you  build with the SDK. I think you are missing  build steps.

**Comment by levone1** [comment]
> Starts fine if you build with the SDK. I think you are missing build steps.

ok. I just used spec file in source zip...
